name: Msg
version: 1.4.3
description: https://www.spigotmc.org/resources/msg-plugin.80931/
website: https://www.spigotmc.org/resources/msg-plugin.80931/
main: com.mickymaus209.msg.spigot.Msg
author: MickyMaus209
softdepend:
  - PlaceHolderAPI
commands:
  msg:
    description: Sends a private message
  reply:
    description: Replies to a private message